module.exports = {
    Base: require('./Base'),
    BusinessContact: require('./BusinessContact'),
    Chat: require('./Chat'),
    ClientInfo: require('./ClientInfo'),
    Contact: require('./Contact'),
    GroupChat: require('./GroupChat'),
    Location: require('./Location'),
    Message: require('./Message'),
    MessageMedia: require('./MessageMedia'),
    PrivateChat: require('./PrivateChat'),
    PrivateContact: require('./PrivateContact'),
    GroupNotification: require('./GroupNotification'),
    Label: require('./Label.js'),
    Order: require('./Order'),
    Product: require('./Product'),
    Call: require('./Call'),
    Buttons: require('./Buttons'),
    List: require('./List'),
    Payment: require('./Payment'),
    Reaction: require('./Reaction'),
};
