# Issue Labels
- name: 'bug'
  color: '#d73a4a'
  description: 'Something is broken'
- name: 'feature request'
  color: '#a2eeef'
  description: 'Request for a new feature'

# Status Labels
- name: 'in progress'
  color: '#fbca04'
  description: 'Work in progress'
- name: 'in review'
  color: '#0e8a16'
  description: 'Awaiting review'
- name: 'merge ready'
  color: '#0e8a16'
  description: 'Ready to merge'
- name: 'blocked'
  color: '#d13917'
  description: 'Blocked by another issue'
- name: 'discussion'
  color: '#d876e3'
  description: 'Needs discussion'
- name: 'approved'
  color: '#11EA91'
  description: 'Confirmed by maintainers'
- name: 'stale'
  color: '#bfd4f2'
  description: 'Inactive for a while'
- name: 'waiting for a response'
  color: '#BE4422'
  description: 'Waiting for author response'
- name: 'waiting for testers'
  color: '#7d006a'
  description: 'Needs testing'

# Priority & Help
- name: 'good first issue'
  color: '#7057ff'
  description: 'Beginner-friendly issue'
- name: 'help wanted'
  color: '#008672'
  description: 'Community help needed'
- name: 'high priority'
  color: '#00DFA8'
  description: 'Important issue'

# Bug Issues
- name: 'issued low'
  color: '#d4c5f9'
  description: 'Low impact issue'
- name: 'issued medium'
  color: '#d4c5f9'
  description: 'Medium impact issue'
- name: 'issued high'
  color: '#d4c5f9'
  description: 'High impact issue'

# Resolution
- name: 'duplicate'
  color: '#cfd3d7'
  description: 'Already reported'
- name: 'invalid'
  color: '#e4e669'
  description: 'Not a valid issue'
- name: 'wontfix'
  color: '#ffffff'
  description: 'Will not be fixed'

# Type of Change
- name: 'api changes'
  color: '#5319e7'
  description: 'API modifications'
- name: 'dependencies'
  color: '#0366d6'
  description: 'Dependency updates'
- name: 'security'
  color: '#ee0701'
  description: 'Security related'
- name: 'performance'
  color: '#ff6b6b'
  description: 'Performance improvements'
- name: 'error handling'
  color: '#f9d0c4'
  description: 'Error handling updates'
- name: 'typings'
  color: '#1d76db'
  description: 'Type definitions'
- name: 'interactions'
  color: '#c5def5'
  description: 'Interaction changes'
- name: 'breaking change'
  color: '#E9314A'
  description: 'Breaks existing behavior'

# Bots & Automation
- name: 'dependabot'
  color: '#0366d6'
  description: 'Dependabot PR'
- name: 'depfu'
  color: '#0000ff'
  description: 'Depfu PR'

# Code & Build
- name: 'tests'
  color: '#bfd4f2'
  description: 'Test related'
- name: 'build'
  color: '#0075ca'
  description: 'Build system'
- name: 'ci'
  color: '#0075ca'
  description: 'CI pipeline'
- name: 'infra'
  color: '#d4c5f9'
  description: 'Infrastructure'
- name: 'styles'
  color: '#ffc0cb'
  description: 'Code style'
- name: 'ui'
  color: '#ffaad4'
  description: 'UI changes'
- name: 'utility'
  color: '#ededed'
  description: 'Utility code'
- name: 'chore'
  color: '#fef2c0'
  description: 'Maintenance task'

# Quality & Review
- name: 'AI pr'
  color: '#b60205'
  description: 'AI-assisted PR; Review very carefully!'
- name: 'bad pr'
  color: '#B60205'
  description: 'Below project standards'

# Project Specific
- name: 'docs'
  color: '#0075ca'
  description: 'Documentation changes'
- name: 'whatsapp bug'
  color: '#1d76db'
  description: 'WhatsApp Web bug'
- name: 'whatsapp change'
  color: '#25D366'
  description: 'WhatsApp Web change'
