# Issue Labels
- name: 'bug'
  color: '#d73a4a'
  description: "Something isn't working"
- name: 'feature request'
  color: '#a2eeef'

# Status Labels
- name: 'in progress'
  color: '#fbca04'
- name: 'in review'
  color: '#0e8a16'
- name: 'merge ready'
  color: '#0e8a16'
- name: 'blocked'
  color: '#d13917'
  description: 'Waiting on another issue to be resolved'
- name: 'discussion'
  color: '#d876e3'
- name: 'approved'
  color: '#11EA91'
  description: 'An issue that has been confirmed by one of the collaborators and acknowledged as relevant'
- name: 'stale'
  color: '#bfd4f2'
- name: 'waiting for a response'
  color: '#BE4422'
  description: 'Waiting for a response from the author of an issue or a PR'
- name: 'waiting for testers'
  color: '#7d006a'
  description: 'Waiting for other people test this PR in other envs'

# Priority & Help
- name: 'good first issue'
  color: '#7057ff'
- name: 'help wanted'
  color: '#008672'
  description: 'Extra attention is needed'
- name: 'high priority'
  color: '#00DFA8'

# Bug Issues
- name: 'issued low'
  color: '#d4c5f9'
- name: 'issued medium'
  color: '#d4c5f9'
- name: 'issued high'
  color: '#d4c5f9'

# Resolution
- name: 'duplicate'
  color: '#cfd3d7'
  description: 'This issue or pull request already exists'
- name: 'invalid'
  color: '#e4e669'
- name: 'wontfix'
  color: '#ffffff'
  description: 'This will not be worked on'

# Type of Change
- name: 'api changes'
  color: '#5319e7'
- name: 'dependencies'
  color: '#0366d6'
  description: 'Pull requests that update a dependency file'
- name: 'security'
  color: '#ee0701'
- name: 'performance'
  color: '#ff6b6b'
- name: 'error handling'
  color: '#f9d0c4'
- name: 'typings'
  color: '#1d76db'
- name: 'interactions'
  color: '#c5def5'
- name: 'breaking change'
  color: '#E9314A'
  description: 'Fix or feature that would cause existing functionality to change.'

# Bots & Automation
- name: 'dependabot'
  color: '#0366d6'
- name: 'depfu'
  color: '#0000ff'

# Code & Build
- name: 'tests'
  color: '#bfd4f2'
- name: 'build'
  color: '#0075ca'
- name: 'ci'
  color: '#0075ca'
- name: 'infra'
  color: '#d4c5f9'
- name: 'styles'
  color: '#ffc0cb'
- name: 'ui'
  color: '#ffaad4'
- name: 'utility'
  color: '#ededed'
- name: 'chore'
  color: '#fef2c0'

# Quality & Review
- name: 'AI pr'
  color: '#b60205'
  description: 'Not necessarily a bad PR, but it should be reviewed with extra caution.'
- name: 'bad pr'
  color: '#B60205'
  description: 'A PR that is not up to the standards of the project and needs significant work before it can be merged.'

# Project Specific
- name: 'documentation'
  color: '#0075ca'
- name: 'whatsapp bug'
  color: '#1d76db'
  description: 'A bug in WhatsApp Web; issues under this label exist solely to inform users about known information.'
- name: 'whatsapp change'
  color: '#25D366'
  description: 'A change has occurred in WhatsApp Web that breaks existing functionality.'

# Packages & Apps
# Note: May change this repo in the future to a mono repo structure
- name: 'packages:whatsapp-web.js'
  color: '#5663e9'
- name: 'apps:website'
  color: '#2e7d32'
