api changes:
  - changed-files:
      - any-glob-to-any-file:
          - src/*
          - src/**/*
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json
tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/*
          - tests/**/*
docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/*
          - docs/**/*
          - '**/*.md'
          - .jsdoc.json
infra:
  - changed-files:
      - any-glob-to-any-file:
          - .github/*
          - .github/**/*
ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/*
          - .github/workflows/**/*
typings:
  - changed-files:
      - any-glob-to-any-file:
          - index.d.ts
          - '**/*.d.ts'
utility:
  - changed-files:
      - any-glob-to-any-file:
          - src/util/*
          - src/util/**/*
build:
  - changed-files:
      - any-glob-to-any-file:
          - tools/*
          - tools/**/*
          - .eslintrc.json
          - .eslintignore
          - .prettierrc.json
          - .prettierignore
          - .editorconfig
          - .gitignore
          - .gitattributes
          - .commitlint.config.js
chore:
  - changed-files:
      - any-glob-to-any-file:
          - .env.example
          - .npmignore
          - LICENSE
          - .github/FUNDING.yml
          - .github/CODE_OF_CONDUCT.md
          - .github/ISSUE_TEMPLATE/*
          - .github/ISSUE_TEMPLATE/**/*
